# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0026_client_multiple_response_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='encrypt_token',
            field=models.BooleanField(default=False, help_text='If enabled, the token_encryption_key will be used to encrypt ID Tokens', verbose_name='Should encrypt ID Tokens?'),
        ),
        migrations.AddField(
            model_name='client',
            name='jwe_alg',
            field=models.CharField(choices=[('RSA1_5', 'RSA1_5'), ('RSA-OAEP', 'RSA-OAEP'), ('RSA-OAEP-256', 'RSA-OAEP-256')], default='RSA-OAEP', help_text='Algorithm used to encrypt ID Tokens.', max_length=12, verbose_name='JWE Algorithm'),
        ),
        migrations.AddField(
            model_name='client',
            name='jwe_enc',
            field=models.CharField(choices=[('A128CBC-HS256', 'A128CBC-HS256'), ('A192CBC-HS384', 'A192CBC-HS384'), ('A256CBC-HS512', 'A256CBC-HS512')], default='A256CBC-HS512', help_text='Algorithm used to perform authenticated encryption to ID Tokens.', max_length=13, verbose_name='JWE Authenticated Encryption algorithm'),
        ),
        migrations.AddField(
            model_name='client',
            name='token_encryption_key',
            field=models.TextField(default='', help_text="Paste the Client's public RSA Key here.", verbose_name='Token Encryption Key'),
        ),
    ]
