# Generated by Django 3.0.4 on 2020-03-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0029_auto_20190606_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='_amr',
            field=models.CharField(max_length=255, null=True, verbose_name='Authentication Method Reference'),
        ),
        migrations.AddField(
            model_name='token',
            name='acr',
            field=models.CharField(max_length=255, null=True, verbose_name='Authentication Context Reference'),
        ),
    ]
